blog_project/account/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import home,ArticleList


app_name = 'account'
urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    # path('logout/', views.LogoutView.as_view(), name='logout'),

    # path('password_change/', views.PasswordChangeView.as_view(),
    #      name='password_change'),
    # path('password_change/done/', views.PasswordChangeDoneView.as_view(),
    #      name='password_change_done'),

    # path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', views.PasswordResetDoneView.as_view(),
    #      name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(),
    #      name='password_reset_confirm'),
    # path('reset/done/', views.PasswordResetCompleteView.as_view(),
    #      name='password_reset_complete'),
]

urlpatterns += [
    path('home/',ArticleList.as_view(), name='home')
]

blog_project/blog/urls.py
from django.urls import path
from .views import category, author, ArticleList, ArticleDetail

app_name = "blog"
urlpatterns = [
    path('', ArticleList.as_view(), name="home"),
    path('p<int:page>', ArticleList.as_view(), name="home"),
    path('article/<slug:slug>', ArticleDetail.as_view(), name="detail"),
    path('category/<slug:slug>', category, name="category"),
    path('category/<slug:slug>/p<int:page>', category, name="category"),
    path('auth/<slug:username>', author, name="author"),
    path('auth/<slug:username>/p<int:page>', author, name="author"),

]

blog_project/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_project/account/models.py
from django.db import models

# Create your models here.

blog_project/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.html import format_html
from django.utils import timezone
from extensions.utils import jalali_convertor

# Create your models here.
class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)

class Category(models.Model):
    parent = models.ForeignKey('self', default=None, null=True, blank=True, on_delete=models.SET_NULL, related_name='children',verbose_name='دسته والد' )
    title = models.CharField(max_length=200, verbose_name="عنوان دسته بندی")
    slug = models.SlugField(max_length=100, unique=True, verbose_name="آدرس دسته بندی")
    status = models.BooleanField(default=True, verbose_name="آیا نمایش داده شود؟")
    position = models.IntegerField(verbose_name="پوزیشن")

    objects = CategoryManager()

    class Meta:
        verbose_name = "دسته"
        verbose_name_plural = "دسته ها"
        ordering = ['parent_id','position']
    def __str__(self):
        return self.title

class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status="p")

class Article(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش نویس'),
        ('p', 'منتشر شده'),
    )
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name="articles", verbose_name="نویسنده")
    title = models.CharField(max_length=200, verbose_name="عنوان")
    slug = models.SlugField(max_length=100, unique=True,verbose_name="آدرس مقاله")
    category = models.ManyToManyField(Category, verbose_name="دسته بندی", related_name="articles")
    description = models.TextField(verbose_name="محتوا")
    thumbnail = models.ImageField(upload_to="images",verbose_name="تصویر مقاله")
    publish = models.DateTimeField(default=timezone.now,verbose_name="زمان انتشار")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES,verbose_name="وضعیت")
    
    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"

    def __str__(self):
        return self.title

    def jpublish(self):
        return jalali_convertor(self.publish)
    jpublish.short_description = "زمان انتشار"

    def category_published(self):
        return self.category.filter(status=True)

    #نمایش عکس های بند انگشتی در پنل ادمین
    def thumbnail_tag(self):
        return format_html("<img width=140 src='{}' style='border-radius: 5px;'>".format(self.thumbnail.url))
    thumbnail_tag.short_description ="عکس بند انگشتی"


    objects = ArticleManager()



class TitleSettings(models.Model):
    POSITION_CHOICES = (
        ('site', 'عنوان سایت'),
        ('navbar', 'لوگو منو اصلی'),
        ('copyright', 'کپی رایت'),
    )
    title = models.CharField(max_length=200, verbose_name="عنوان")
    position = models.CharField(max_length=50, verbose_name="موقعیت در سایت", primary_key=True, choices=POSITION_CHOICES)

    class Meta:
        verbose_name = "تنظیمات"
        verbose_name_plural = "تنظیمات"

    def __str__(self):
        return self.title

blog_project/account/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView
from blog.models import Article

# Create your views here.
@login_required
def home(request):
    return render(request,'registration/home.html')


class ArticleList(LoginRequiredMixin, ListView):
    queryset = Article.objects.all()
    template_name = "registration/home.html"

blog_project/blog/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse, Http404
from .models import Article, Category
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.

#first page of site
# def home(request, page=1):

#     article_list = Article.objects.published().order_by('-publish')
#     paginator = Paginator(article_list, 3)

#     try:
#         articles = paginator.page(page)
#     except PageNotAnInteger:
#         articles = paginator.page(1)
#     except EmptyPage:
#         articles = paginator.page(paginator.num_pages)
    
#     context = {
#         "articles" : articles,
        
            
#     }
#     return render(request, 'blog/home.html',context)

class ArticleList(ListView):
    # model = Article
    template_name = 'blog/home.html'
    context_object_name = "articles"
    queryset = Article.objects.published()
    paginate_by = 3

# def detail(request, slug):
#     context = {
#         "article" : get_object_or_404(Article.objects.published(), slug=slug)            
#     }
#     return render(request, 'blog/detail.html',context)

class ArticleDetail(DetailView):
    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Article.objects.published(), slug=slug)


def category(request, slug, page=1):
    category_obj = get_object_or_404(Category, slug=slug, status=True)
    category_list = category_obj.articles.published()
    paginator = Paginator(category_list, 3)

    try:
        articles_cg = paginator.page(page)
    except PageNotAnInteger:
        articles_cg = paginator.page(1)
    except EmptyPage:
        articles_cg = paginator.page(paginator.num_pages)
    
    context = {
        "category" : category_obj,
        "articles" : articles_cg,            
    }
    return render(request, 'blog/category.html',context)



def author(request, username, page=1):
    author_obj = get_object_or_404(User, username = username)
    author_list = author_obj.articles.published()
    paginator = Paginator(author_list, 3)

    try:
        articles_cg = paginator.page(page)
    except PageNotAnInteger:
        articles_cg = paginator.page(1)
    except EmptyPage:
        articles_cg = paginator.page(paginator.num_pages)
    
    context = {
        "author" : author_obj,
        "articles" : articles_cg,            
    }
    return render(request, 'blog/author.html',context)

blog_project/blog/templates/blog/detail.html
{% extends 'blog/base.html'%}

{% block title %} | {{article.title}}{% endblock %}


{% block main %}
<!-- Page Header -->
  <header class="masthead" style="background-image: url('{{article.thumbnail.url}}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>{{article.title}}</h1>
            <span class="subheading">{{article.publish}}</span>
          </div>
        </div>
      </div>
    </div>
  </header>
<!-- Post Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto text-justify">
        {{article.description|linebreaks}}
      </div>
    </div>
  </div>
</article>
{% endblock %}

blog_project/blog/templates/blog/home.html
{% extends 'blog/base.html'%}

{% load static %}

{% block main %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{% static "blog/img/home-bg.jpg" %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>وبلاگ جنگو</h1>
            <span class="subheading">قدرت گرفته از پایتون و جنگو</span>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
      {% if not articles %}
      <h3 class="alert alert-dark text-center"> متاسفانه مقاله ای برا نمایش وجود ندارد</h3>
      {% endif %}
      {% for article in articles %}
        <div class="post-preview">
            <a href="{% url 'blog:detail' article.slug %}">
              <h2 class="post-title">
                {{article.title}}
              </h2>
              <h3 class="post-subtitle text-justify">
                {{article.description|truncatewords:30}}
              </h3>
            </a>
            <p class="post-meta">نوشته شده توسط
              <a href="{% url 'blog:author' article.author %}">{{article.author.get_full_name}}</a>
              {{article.jpublish}}</p>
              <div>
                {% for cat in article.category_published.all %}
                <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}}</a>
                {% endfor %}
              </div>
          </div>
          <hr>
      {% endfor %}
        <!-- Pager -->
      <!--
        <div class="clearfix" >
          <a class="btn btn-primary float-left" href="#">پست های قدیمی &rarr;</a>
        </div>
      </div>
    </div>
  </div> -->
<nav aria-label="Page navigation">
{% if articles.has_other_pages %}
  <ul class="pagination justify-content-center ">
    {% if articles.has_previous %}
      <li class="page-item">
        <a class="page-link" aria-label="Previous" href="{% url 'blog:home' articles.previous_page_number %}">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">قبلی</a>
    </li>
    {% endif %}
    {% for i in articles.paginator.page_range %}
      {% if articles.number == i %}
        <li class="page-item active">
          <a class="page-link" href="#">{{i}} <span class="sr-only">(current)</span></a>
        </li>
      {% else %}
      <li class="page-item"><a class="page-link" href="{% url 'blog:home' i %}">{{i}}</a></li>
      {% endif %}
    {% endfor %}
    {% if articles.has_next %}
    <li class="page-item">
      <a class="page-link" href="{% url 'blog:home' articles.next_page_number %}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">بعدی</a>
    </li>
    {% endif %}
  </ul>
{% endif %}
</nav>
{% endblock %}

blog_project/templates/blog/article_detail.html
{% extends 'blog/base.html'%}

{% block title %} | {{article.title}}{% endblock %}


{% block main %}
<!-- Page Header -->
  <header class="masthead" style="background-image: url('{{article.thumbnail.url}}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>{{article.title}}</h1>
            <span class="subheading">{{article.publish}}</span>
          </div>
        </div>
      </div>
    </div>
  </header>
<!-- Post Content -->
<article>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto text-justify">
        {{article.description|linebreaks}}
      </div>
    </div>
  </div>
</article>
{% endblock %}

blog_project/templates/blog/article_list.html
{% extends 'blog/base.html'%}

{% load static %}

{% block main %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{% static "blog/img/home-bg.jpg" %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>وبلاگ جنگو</h1>
            <span class="subheading">قدرت گرفته از پایتون و جنگو</span>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-10 mx-auto">
      {% if not articles %}
      <h3 class="alert alert-dark text-center"> متاسفانه مقاله ای برا نمایش وجود ندارد</h3>
      {% endif %}
      {% for article in articles %}
        <div class="post-preview">
            <a href="{% url 'blog:detail' article.slug %}">
              <h2 class="post-title">
                {{article.title}}
              </h2>
              <h3 class="post-subtitle text-justify">
                {{article.description|truncatewords:30}}
              </h3>
            </a>
            <p class="post-meta">نوشته شده توسط
              <a href="{% url 'blog:author' article.author %}">{{article.author.get_full_name}}</a>
              {{article.jpublish}}</p>
              <div>
                {% for cat in article.category_published.all %}
                <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}}</a>
                {% endfor %}
              </div>
          </div>
          <hr>
      {% endfor %}
     
        <!-- Pager -->
      <!--
        <div class="clearfix" >
          <a class="btn btn-primary float-left" href="#">پست های قدیمی &rarr;</a>
        </div>
      </div>
    </div>
  </div> -->
<nav aria-label="Page navigation">
{% if page_obj.has_other_pages %}
  <ul class="pagination justify-content-center ">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" aria-label="Previous" href="{% url 'blog:home' page_obj.previous_page_number %}">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">قبلی</a>
    </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active">
          <a class="page-link" href="#">{{i}} <span class="sr-only">(current)</span></a>
        </li>
      {% else %}
      <li class="page-item"><a class="page-link" href="{% url 'blog:home' i %}">{{i}}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="{% url 'blog:home' page_obj.next_page_number %}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">بعدی</a>
    </li>
    {% endif %}
  </ul>
{% endif %}
</nav>
{% endblock %}

blog_project/templates/blog/author.html
{% extends 'blog/base.html'%}

{% load static %}

{% block main %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{% static "blog/img/home-bg.jpg" %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>وبلاگ جنگو</h1>
            <span class="subheading">قدرت گرفته از پایتون و جنگو</span>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
          <h3 class="alert alert-info text-center"> دسته بندی:{{author.get_full_name}}</h3>
      {% for article in articles %}
        <div class="post-preview">
            <a href="{% url 'blog:detail' article.slug %}">
              <h2 class="post-title">
                {{article.title}}
              </h2>
              <h3 class="post-subtitle">
                {{article.description|truncatewords:30}}
              </h3>
            </a>
            <p class="post-meta">نوشته شده توسط
              <a href="#">{{علی}}</a>
              {{article.jpublish}}</p>
              <div>
                {% for cat in article.category.active %}
                <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}}</a>
                {% endfor %}
              </div>
          </div>
          <hr>
      {% endfor %}
        <!-- Pager -->
        <nav aria-label="Page navigation">
          {% if articles.has_other_pages %}
            <ul class="pagination justify-content-center ">
              {% if articles.has_previous %}
                <li class="page-item">
                  <a class="page-link" aria-label="Previous" href="{% url 'blog:author' author.username articles.previous_page_number %}">
                    <span aria-hidden="true">&laquo;</span>
                  </a>
                </li>
              {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">قبلی</a>
              </li>
              {% endif %}
              {% for i in articles.paginator.page_range %}
                {% if articles.number == i %}
                  <li class="page-item active">
                    <a class="page-link" href="#">{{i}} <span class="sr-only">(current)</span></a>
                  </li>
                {% else %}
                <li class="page-item"><a class="page-link" href="{% url 'blog:author' author.username i %}">{{i}}</a></li>
                {% endif %}
              {% endfor %}
              {% if articles.has_next %}
              <li class="page-item">
                <a class="page-link" href="{% url 'blog:author' author.username articles.next_page_number %}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
              {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">بعدی</a>
              </li>
              {% endif %}
            </ul>
          {% endif %}
          </nav>

{% endblock %}

blog_project/templates/blog/base.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>وبلاگ جنگویی</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'blog/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'blog/css/clean-blog.min.css' %}" rel="stylesheet">
  <link href="{% static 'blog/css/rtl.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:home' %}">وبلاگ جنگویی</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          {% category_navbar %}
        </ul>
      </div>
    </div>
  </nav>

  

  {% block main %}
  {% endblock %}

  <hr>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'blog/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'blog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'blog/js/clean-blog.min.js' %}"></script>

</body>

</html>

blog_project/templates/blog/category.html
{% extends 'blog/base.html'%}

{% load static %}

{% block main %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{% static "blog/img/home-bg.jpg" %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>وبلاگ جنگو</h1>
            <span class="subheading">قدرت گرفته از پایتون و جنگو</span>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-10 mx-auto">
          <h3 class="alert alert-info text-center"> دسته بندی:{{category.title}}</h3>
      {% for article in articles %}
        <div class="post-preview">
            <a href="{% url 'blog:detail' article.slug %}">
              <h2 class="post-title">
                {{article.title}}
              </h2>
              <h3 class="post-subtitle">
                {{article.description|truncatewords:30}}
              </h3>
            </a>
            <p class="post-meta">نوشته شده توسط
              <a href="#">علی</a>
              {{article.jpublish}}</p>
              <div>
                {% for cat in article.category.active %}
                <a href="{% url 'blog:category' cat.slug %}">#{{cat.title}}</a>
                {% endfor %}
              </div>
          </div>
          <hr>
      {% endfor %}
        <!-- Pager -->
        <nav aria-label="Page navigation">
          {% if articles.has_other_pages %}
            <ul class="pagination justify-content-center ">
              {% if articles.has_previous %}
                <li class="page-item">
                  <a class="page-link" aria-label="Previous" href="{% url 'blog:category' category.slug articles.previous_page_number %}">
                    <span aria-hidden="true">&laquo;</span>
                  </a>
                </li>
              {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">قبلی</a>
              </li>
              {% endif %}
              {% for i in articles.paginator.page_range %}
                {% if articles.number == i %}
                  <li class="page-item active">
                    <a class="page-link" href="#">{{i}} <span class="sr-only">(current)</span></a>
                  </li>
                {% else %}
                <li class="page-item"><a class="page-link" href="{% url 'blog:category' category.slug i %}">{{i}}</a></li>
                {% endif %}
              {% endfor %}
              {% if articles.has_next %}
              <li class="page-item">
                <a class="page-link" href="{% url 'blog:category' category.slug articles.next_page_number %}" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
              {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">بعدی</a>
              </li>
              {% endif %}
            </ul>
          {% endif %}
          </nav>

{% endblock %}

blog_project/templates/blog/partials/category_navbar.html
<ul class="navbar-nav">
<li class="nav-item">
    <a class="nav-link" href="{% url 'blog:home' %}">خانه</a>
  </li>
  {% for category in categories %}
  {% if category.parent == None %}

    {% if category.children.all %}
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="{% url 'blog:category' category.slug %}" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        {{category.title}}
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
      {% for cat in category.children.all%}
        
          <a class="dropdown-item" href="{% url 'blog:category' cat.slug %}">{{cat.title}}</a>


      {% endfor %}
    </div>
  </li>
  {% else %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'blog:home' %}">{{category.title}}</a>
  </li>
    {% endif %}
  {% endif %}

  {% endfor %}
</ul>

<!--
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand" href="{% url 'blog:home' %}">وبلاگ جنگویی</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown navbarResponsive">
    <ul class="navbar-nav ml auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">خانه <span class="sr-only">(current)</span></a>
      </li>
  {% for category in categories %}
    {% if category.parent == None %}
      {% if category.children.all %}
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{category.title}}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink"></div>
        {% for cat in category.children.all %}
        
          <a class="dropdown-item" href="#">{{cat.title}}</a>
        
        {% endfor %}
      </div>
      </li>

      {% endif %}

      
      <li class="nav-item">
        <a class="nav-link" href="#">{{catgeory.title}}</a>
      </li>

    {% endif%}
      
      
      
      
  {% endfor %}
    </ul>
    </div>
  </div>
</nav>
-->